services:
  web: 
    build: .
    ports: 
      - "8000:8000"
    environment:
      - "MONGODB_URI=mongodb://db:27017/"
  db:
    image: "mongo"
    volumes:
      - nflscores-data:/data/db


volumes:
  nflscores-data:
