version: '3'
services:
  web: 
    build: .
    ports: 
      - "8000:8000"
  db:
    image: "mongo"
    volumes:
      - db-data:/nflscores
  proxy:
    build: ./proxy
    ports:
      - "80:80"


volumes:
  db-data: